version: '3'

services:
  influxdb:
    image: influxdb:2.0.4
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup      
      - DOCKER_INFLUXDB_INIT_USERNAME=admin      
      - DOCKER_INFLUXDB_INIT_PASSWORD=password      
      - DOCKER_INFLUXDB_INIT_ORG=myorgname
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucketname
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

volumes:
  influxdb-storage:
