version: '3'

services:
  influxdb:
          #image: influxdb:1.0
    image: influxdb:2.0.4
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
        #- ./influxdb.conf:/etc/influxdb/influxdb.conf
        #- ./types.db:/usr/share/collectd/types.db:ro
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
        #entrypoint:
        #- /bin/cat
        #- /etc/hosts
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
